# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "#Josh2020"
email: josh.bondy@codekiwi.com
description: The time has come again for me to pack up my life and head off on loosely planned and poorly researched adventures - I'm not sure whats in store but I'm sure it'll be entertaining, I hope you join me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://votejosh2020.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codekiwi
github_username:  codekiwi
permalink: /:categories/:year/:month/:title
# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - any_additional_item # any user-specific listing goes at the end
category_titles:
    antipodes: 'Antipodes'
    europe: 'Europe'
    asia: 'Asia'
    americas: 'Americas'
    musings: 'Musings'
    projects: 'Projects'
# Google services
google_analytics: UA-25638324-2
author: Josh Bondy
