# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "#Josh2020"
email: josh.bondy@codekiwi.com
description: So here I am, embarking on a journey into places unknown, to travel with people I have never met, to do work that I have not secured for clients and projects that, at this stage don’t exist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://votejosh2020.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codekiwi
github_username:  codekiwi
permalink: /:categories/:year/:month/:title
# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
category_titles:
    antipodes: 'Antipodes'
    europe: 'Europe'
    asia: 'Asia'
    musings: 'Musings'
    projects: 'Projects'
# Google services
google_analytics: UA-25638324-2
author: Josh Bondy
